const SUPABASE_URL      = "https://siybrsxreftmbbhxujmp.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_0Ebp443kgM-sjp0Q5WgLBg_HBVlcCEg";

const state = {
  screen:    "intro",
  deck:      [],
  cursor:    0,
  votes:     [],
  phase:     "voting",
  sessionId: null,
};

function shuffleArray(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function initGame() {
  state.deck      = shuffleArray(SAMPLES).slice(0, 100);
  state.cursor    = 0;
  state.votes     = [];
  state.phase     = "voting";
  state.screen    = "game";
  state.sessionId = crypto.randomUUID();
  render();
}

function render() {
  if (state.screen === "intro")   renderIntro();
  if (state.screen === "game")    renderGame();
  if (state.screen === "results") renderResults();
}

// ── Intro ────────────────────────────────────────────────────────────────────

function renderIntro() {
  document.getElementById("app").innerHTML = `
    <div class="intro">
      <div class="intro-icon">🤖</div>
      <h1>Human or AI?</h1>
      <p class="intro-desc">
        Read a tweet, LinkedIn post, or blog excerpt — then decide:<br>
        was it written by a human or generated by AI?
      </p>
      <ul class="intro-rules">
        <li>Vote on at least <strong>10 samples</strong> to unlock your score</li>
        <li>You can keep going up to <strong>100 samples</strong></li>
        <li>Find out how good you really are at spotting AI</li>
      </ul>
      <button id="btn-start" class="btn btn-start">Start</button>
    </div>
  `;
  document.getElementById("btn-start").addEventListener("click", initGame);
}

// ── Game ─────────────────────────────────────────────────────────────────────

function escapeHTML(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function buildCard(sample) {
  const text = escapeHTML(sample.text).replace(/\n/g, "<br>");

  if (sample.type === "tweet") {
    return `
      <div class="card card--tweet">
        <div class="tweet-header">
          <span class="tweet-bird">🐦</span>
        </div>
        <div class="tweet-body">
          <p class="tweet-text">${text}</p>
          <div class="tweet-actions">
            <span>💬 Reply</span><span>🔁 Repost</span><span>❤️ Like</span>
          </div>
        </div>
      </div>`;
  }

  if (sample.type === "linkedin") {
    return `
      <div class="card card--linkedin">
        <p class="li-text">${text}</p>
        <div class="li-actions">
          <span>👍 Like</span><span>💡 Insightful</span><span>♻️ Repost</span>
        </div>
      </div>`;
  }

  // blog
  return `
    <div class="card card--blog">
      <div class="blog-badge">Blog Excerpt</div>
      <p class="blog-text">${text}</p>
    </div>`;
}

function renderGame() {
  const sample    = state.deck[state.cursor];
  const voted     = state.votes.length;
  const total     = state.deck.length;
  const progress  = Math.min(Math.round((voted / 10) * 100), 100);
  const progressLabel = voted < 10
    ? `${voted} / 10 minimum`
    : `${voted} voted`;

  const feedbackHTML = state.phase === "feedback" ? buildFeedback() : "";
  const mainActionsHTML = state.phase === "voting"
    ? `<div class="vote-actions">
         <button id="btn-human" class="btn btn-human">Human Written</button>
         <button id="btn-ai"    class="btn btn-ai">AI Generated</button>
       </div>`
    : `<div class="next-actions">
         <button id="btn-next" class="btn btn-next">Next →</button>
       </div>`;

  const scoreLocked = voted < 10;
  const scoreHTML = `<div class="score-action">
    <button id="btn-score" class="btn btn-score${scoreLocked ? " btn-score--locked" : ""}"${scoreLocked ? " disabled" : ""}>See My Score</button>
  </div>`;

  const cardFeedbackClass = state.phase === "feedback"
    ? (state.votes[state.votes.length - 1].correct ? " card-correct" : " card-wrong")
    : "";

  document.getElementById("app").innerHTML = `
    <div class="game">
      <div class="progress-row">
        <span class="progress-label">${progressLabel}</span>
        <span class="progress-count">${state.cursor + 1} / ${total}</span>
      </div>
      <div class="progress-track">
        <div class="progress-fill" style="width:${progress}%"></div>
      </div>
      <div class="type-badge type-badge--${sample.type}">${sample.type}</div>
      <div class="card-wrap${cardFeedbackClass}">
        ${buildCard(sample)}
      </div>
      ${feedbackHTML}
      ${mainActionsHTML}
      ${scoreHTML}
    </div>
  `;

  if (state.phase === "voting") {
    document.getElementById("btn-human").addEventListener("click", () => handleVote(false));
    document.getElementById("btn-ai").addEventListener("click",    () => handleVote(true));
  } else {
    document.getElementById("btn-next").addEventListener("click", handleNext);
  }
  const scoreBtn = document.getElementById("btn-score");
  if (scoreBtn && !scoreBtn.disabled) scoreBtn.addEventListener("click", handleSeeScore);
}

function buildFeedback() {
  const last    = state.votes[state.votes.length - 1];
  const correct = last.correct;
  const label   = last.isAI ? "AI Generated" : "Human Written";
  return `
    <div class="feedback ${correct ? "feedback--correct" : "feedback--wrong"}">
      <span class="feedback-icon">${correct ? "✓" : "✗"}</span>
      <span class="feedback-text">
        ${correct ? "Correct!" : "Wrong."} This was <strong>${label}</strong>.
      </span>
    </div>`;
}

function handleVote(guessedAI) {
  const sample = state.deck[state.cursor];
  state.votes.push({
    id:        sample.id,
    type:      sample.type,
    isAI:      sample.isAI,
    guessedAI: guessedAI,
    correct:   guessedAI === sample.isAI,
  });
  state.phase = "feedback";
  renderGame();
}

function handleNext() {
  if (state.votes.length >= 100 || state.cursor + 1 >= state.deck.length) {
    state.screen = "results";
    render();
    return;
  }
  state.cursor++;
  state.phase = "voting";
  renderGame();
}

function handleSeeScore() {
  state.screen = "results";
  render();
}

// ── Results ──────────────────────────────────────────────────────────────────

function getTier(accuracy) {
  if (accuracy >= 85) return { label: "AI Whisperer",            emoji: "🔮" };
  if (accuracy >= 70) return { label: "Suspiciously Perceptive", emoji: "🕵️" };
  if (accuracy >= 55) return { label: "Getting Suspicious",      emoji: "🤔" };
  if (accuracy >= 40) return { label: "Coin Flip Energy",        emoji: "🪙" };
  return                     { label: "Easily Fooled",           emoji: "🤖" };
}

function computeScore() {
  const votes   = state.votes;
  const correct = votes.filter(v => v.correct).length;
  const accuracy = (correct / votes.length) * 100;
  const tier    = getTier(accuracy);

  const byType = {};
  for (const t of ["tweet", "linkedin", "blog"]) {
    const tv = votes.filter(v => v.type === t);
    const tc = tv.filter(v => v.correct).length;
    byType[t] = {
      total:    tv.length,
      correct:  tc,
      accuracy: tv.length > 0 ? (tc / tv.length) * 100 : null,
    };
  }

  const wrong = votes.filter(v => !v.correct);
  const missedAI  = wrong.filter(v => v.isAI);   // AI but guessed Human
  const falseAI   = wrong.filter(v => !v.isAI);  // Human but guessed AI
  const errors = {
    total:       wrong.length,
    missedAI:    missedAI.length,
    falseAI:     falseAI.length,
    missedAIPct: wrong.length > 0 ? Math.round((missedAI.length / wrong.length) * 100) : 0,
    falseAIPct:  wrong.length > 0 ? Math.round((falseAI.length  / wrong.length) * 100) : 0,
  };

  return { total: votes.length, correct, accuracy, byType, tier, errors };
}

const db = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

async function submitScore(s) {
  if (SUPABASE_URL.includes("YOUR_")) return;
  const { error } = await db.from("game_results").insert({
    session_id:       state.sessionId,
    total_votes:      s.total,
    correct:          s.correct,
    accuracy:         Math.round(s.accuracy * 100) / 100,
    missed_ai:        s.errors.missedAI,
    false_ai:         s.errors.falseAI,
    missed_ai_pct:    s.errors.missedAIPct,
    false_ai_pct:     s.errors.falseAIPct,
    tweet_total:      s.byType.tweet.total,
    tweet_correct:    s.byType.tweet.correct,
    linkedin_total:   s.byType.linkedin.total,
    linkedin_correct: s.byType.linkedin.correct,
    blog_total:       s.byType.blog.total,
    blog_correct:     s.byType.blog.correct,
  });
  if (error) return;

  const voteRows = state.votes.map(v => ({
    session_id:  state.sessionId,
    sample_id:   v.id,
    sample_type: v.type,
    is_ai:       v.isAI,
    guessed_ai:  v.guessedAI,
    correct:     v.correct,
  }));
  await db.from("vote_events").insert(voteRows);
}

function typeLabel(t) {
  return { tweet: "Tweets", linkedin: "LinkedIn", blog: "Blog Posts" }[t];
}

function renderResults() {
  const s = computeScore();
  submitScore(s);
  const pct = Math.round(s.accuracy);

  const typeCards = ["tweet", "linkedin", "blog"].map(t => {
    const d = s.byType[t];
    if (d.total === 0) return `
      <div class="stat-card">
        <div class="stat-type">${typeLabel(t)}</div>
        <div class="stat-nodata">No samples</div>
      </div>`;
    const p = Math.round(d.accuracy);
    return `
      <div class="stat-card">
        <div class="stat-type">${typeLabel(t)}</div>
        <div class="stat-fraction">${d.correct} / ${d.total}</div>
        <div class="mini-track"><div class="mini-fill" style="width:${p}%"></div></div>
        <div class="stat-pct">${p}%</div>
      </div>`;
  }).join("");

  const e = s.errors;
  const errorsHTML = e.total === 0
    ? `<div class="error-breakdown"><p class="error-perfect">No wrong answers. Suspicious.</p></div>`
    : `<div class="error-breakdown">
        <h3 class="error-title">Where you went wrong</h3>
        <div class="error-rows">
          <div class="error-row">
            <span class="error-label">AI writing you thought was human</span>
            <span class="error-bar-wrap">
              <span class="error-bar error-bar--missed" style="width:${e.missedAIPct}%"></span>
            </span>
            <span class="error-pct">${e.missedAIPct}%</span>
          </div>
          <div class="error-row">
            <span class="error-label">Human writing you thought was AI</span>
            <span class="error-bar-wrap">
              <span class="error-bar error-bar--false" style="width:${e.falseAIPct}%"></span>
            </span>
            <span class="error-pct">${e.falseAIPct}%</span>
          </div>
        </div>
        <p class="error-note">(as % of your ${e.total} wrong answer${e.total === 1 ? "" : "s"})</p>
      </div>`;

  document.getElementById("app").innerHTML = `
    <div class="results">
      <div class="results-top">
        <div class="tier-emoji">${s.tier.emoji}</div>
        <div class="big-pct">${pct}%</div>
        <div class="tier-label">${s.tier.label}</div>
        <p class="results-sub">You got <strong>${s.correct} of ${s.total}</strong> correct.</p>
      </div>
      <div class="stat-cards">${typeCards}</div>
      ${errorsHTML}
      <button id="btn-again" class="btn btn-start">Play Again</button>
    </div>
  `;
  document.getElementById("btn-again").addEventListener("click", initGame);
}

// ── Boot ─────────────────────────────────────────────────────────────────────
render();
